### ISSUE TITLE
Redirect URL is incorrect if baseURL is other than root

### ISSUE THREAD

**Issue by AmrEldib** [dbouwman/torii-provider-arcgis#8]
If `config.baseURL` is set to a value other `/`, the redirect URL ignores it and just redirects to the root.
This can be resolved by modifying the value of `_currentBaseUrl` at [line 37 of arcgis-oauth-bearer.js](https://github.com/dbouwman/torii-provider-arcgis/blob/master/app/torii-providers/arcgis-oauth-bearer.js#L37) to include `config.baseURL`.
Importing `config` is needed.
I've tested this change on localhost and a github page deploy and it worked.

**Comment by dbouwman** [comment]
@AmrEldib Sorry for not seeing this until now - Thanks for catching this! I ran into this and ended up implementing a slightly more convoluted version, mainly because of idiosyncrasies of some apps we have that are using this addon.

https://github.com/dbouwman/torii-provider-arcgis/blob/master/app/torii-providers/arcgis-oauth-bearer.js#L62-L68

This is now in the latest version.
